const fs = require("fs");
const yaml = require("js-yaml");

function processItems(items) {
  return items.map(item => {
    if (item.id) {
      return {
        type: "doc",
        label: item.label,
        id: item.id
      };
    } else if (item.items) {
      return {
        type: "category",
        label: item.label,
        items: processItems(item.items)
      };
    }
    return null;
  }).filter(Boolean);
}

function yamlToSidebar(yamlData) {
  const data = Array.isArray(yamlData) ? yamlData : Object.values(yamlData);

  return data.map(section => ({
    type: "category",
    label: section.label,
    items: processItems(section.items || [])
  }));
}

function main() {
  try {
    const toc = yaml.load(fs.readFileSync("toc.yaml", "utf8"));

    const sidebar = yamlToSidebar(toc);

    const output = `
    // @ts-check

    // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

    /**
     * Creating a sidebar enables you to:
     - create an ordered group of docs
    - render a sidebar for each doc of that group
    - provide next/previous navigation

    The sidebars can be generated from the filesystem, or explicitly defined here.

    Create as many sidebars as you want.

    @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
    */
    const sidebars = {
      tutorialSidebar: [
        {
          type: 'doc',
          label: 'Tutorial Intro',
          id: 'intro',
        },
        {
          type: 'category',
          label: 'Tutorial - Basics',
          items: [
            {type: 'autogenerated', dirName: 'tutorial-basics'},
          ]
        },
        {
          type: 'category',
          label: 'Tutorial - Extras',
          items: [
            {type: 'autogenerated', dirName: 'tutorial-extras'},
          ]
        },
      ],
      guidesSidebar: ${JSON.stringify(sidebar, null, 2)}
    };\n
    export default sidebars;
    `;

    fs.writeFileSync("sidebars.js", output, "utf8");
    console.log("✅ sidebars.js generated successfully!");
  } catch (e) {
    console.error("❌ Error generating sidebars.js:", e);
  }
}

main();
